### ISSUE TITLE
demo-tassk release should produce cleaned artifacts

### ISSUE THREAD

**Issue by piotrzarzycki21** [DominoVagrant/demo-tasks#20]
When I tool latest source-code of released demo-tasks 0.1.20 I saw there non needed files:
.github
.gitattributes
.gitignore
.release-please-manifest.json

However the most important file was Host.yml which interfere with Host.template.yml. When server was created SHI didn't replace Host.yml, instead uses it as is. Probably I could set that file should be replaced by Host.template.yml in SHI itself, but for now I think it shouldn't be in the prepared artifacts.

**Comment by MarkProminic** [comment]
The following files are needed in order to produce automated github actions and should anyone clone the repo, it contains best practices for the projects.

```
.github
.gitattributes
.gitignore
.release-please-manifest.json
```

In regards to Hosts.yml, I will work on a way to remove this in the released artifact

**Comment by piotrzarzycki21** [comment]
> The following files are needed in order to produce automated github actions and should anyone clone the repo, it contains best practices for the projects.
> 
> ```
> .github
> .gitattributes
> .gitignore
> .release-please-manifest.json
> ```
> 
> In regards to Hosts.yml, I will work on a way to remove this in the released artifact

The assumption is that in released version of demo-tasks user can download package and eventually checkout more thanks to that files ? This is the scenario ?

**Comment by MarkProminic** [comment]
Sorry you are right! I was thinking about my build process not the end result. I can remove them from the artifacts
