### ISSUE TITLE
Missing Copy Permissions for Deployed Database

### ISSUE THREAD

**Issue by JoelProminic** [DominoVagrant/demo-tasks#21]
While working with a demo-tasks instance today (created with Super.Human.Installer), I noticed that a database I deployed did not give copy permissions to the cross-certified user by default.  This is annoying when trying to quickly copy documents or databases.

I found that I had fixed this as part of https://github.com/DominoVagrant/demo/issues/13 , but the relevant lines ([here](https://github.com/DominoVagrant/demo-v1.1/blob/4c8c28dbd7e38da0df2e7236a120c30d8433223f/dist-support/rest_scripts/deploy_database.sh#L78C7-L79) and [here](https://github.com/DominoVagrant/demo-v1.1/blob/4c8c28dbd7e38da0df2e7236a120c30d8433223f/dist-support/rest_scripts/deploy_database.sh#L110-L111)) were not updated in demo-tasks.   

There may be other changes from this issue that were not replicated, so this needs further review.

**Comment by MarkProminic** [comment]
This should be added in the next release
